### ISSUE TITLE
more account lookup consistency issues

### ISSUE THREAD

**Issue by lispc** [privacy-scaling-explorations/zkevm-circuits#1118]
(wip, write some observations, still debugging and fixing)

1. in current begin_tx, we first do transfer than do codehash reading for non-exist check. Is this correct? If transfer.value is non zero, then it will make a non existed account to become an existed account so codehash reading will be incorrect?
2. current Account::is_empty relys on 'store_hashmap.is_empty()'. But in evm, for storage, non-exsit is same with 0. So in fact we need to check 'store_hashmap.values().all( | value | value.is_zero())'. Or a better solution, the the rpc-statedb-building phase, just skip inserting 0 storage values inside statedb
3. when the dst of a transfer is non exist, after this transfer, the account no longer is non exist. Then, from state circuit side, prev_row is Account::CodeHash { is_write: false, prev: 0, value: 0}, next_row is Account::CodeHash { is_write: false, prev: keccak(nil), value: keccak(nil) }. State circuit will be broken..

**Comment by ed255** [comment]
>     1. in current begin_tx, we first do transfer than do codehash reading for non-exist check. Is this correct? 

This is the current implementation, yes.  But this is not how it should be!  We should read the codehash first before touching possibly non-existing accounts.  I added a check to verify this behavior in https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/1092 but obviously it's being skipped here. After a quick check I realized that the check was added in `push_op` but all writes to accounts are done via `push_op_reversible`!  So we should add the check to `push_op_reversible` as well.

> If transfer.value is non zero, then it will make a non existed account to become an existed account so codehash reading will be incorrect? ( i fixed this by changing transfer and codehash reading order)

So there are 2 things to solve here:
1. First check code_hash and determine if account exists or not
2. If account doesn't exist and transfer value > 0, we should write the code_hash to `EMPTY_HASH` before applying the transfer (setting the code_hash to `EMPTY_HASH` will mark the account as existing for the following steps).

>     2. current Account::is_empty relys on 'store_hashmap.is_empty()'. But in evm, for storage, non-exsit is same with 0. So in fact we need to check 'store_hashmap.values().all( | value | value.is_zero())'. Or a better solution, the the rpc-statedb-building phase, just skip inserting 0 storage values inside statedb. Furthur, `statedb.get_storage(acc, k) -> (is_exist: bool, value: Word)`, the is_exist return value should be removed? since there are no 'non-exist' storage value.. 'non-exist' storage value is same thing with zero.

You're right!  I agree that we can remove the `is_exist` return flag from the function `get_storage`.  As for how to avoid having storage keys with 0 value in the storage `HashMap`, I agree that we could skip inserting 0 values in the `rpc-statedb-building` phase.  But we should also consider that an SSTORE that writes a 0 should delete the key-value, so we should modify how writes to storage in the StateDB are done to handle this case.  Maybe replacing `get_storage_mut` by a function that receives the value by parameter, and when it's 0 deletes the key?

>     3. when the dst of a transfer is non exist, after this transfer, the account no longer is non exist. Then, from state circuit side, prev_row is Account::CodeHash { is_write: false, prev: 0, value: 0}, next_row is Account::CodeHash { is_write: false, prev: keccak(nil), value: keccak(nil) }. State circuit will be broken..

Right.  I think that every time an account is created, we must write CodeHash to `EMPTY_HASH`.  This affects: begin_tx and al *CALL* opcodes with value.  So the procedure should be:
1. Read CodeHash of dst
2. If dest non-exist, and value > 0, write CodeHash 0 -> `EMPTY_HASH`.

For CREATE/CREATE2 or begin_tx in contract deployment case, the account creation would do:
1. write CodeHash 0 -> NEW_CODE_HASH
2. write the rest of the account fields (Nonce 0->1, Balance: 0 -> ...)

**Comment by lispc** [comment]
great explanation! 

Does mpt_circuit (or state circuit) need to treat `AccountOp { field_tag: CodeHash, is_write: true, prev_value: 0, value: keccak(nil) }` specially? Since this write rw is not a "normal" rw, it "creates" an account ,instead of changing some value from 0 to keccak(nil)!

**Comment by ed255** [comment]
> great explanation!
> 
> Does mpt_circuit (or state circuit) need to treat `AccountOp { field_tag: CodeHash, is_write: true, prev_value: 0, value: keccak(nil) }` specially? Since this write rw is not a "normal" rw, it "creates" an account ,instead of changing some value from 0 to keccak(nil)!

I think yes!  The `mpt_circuit` should support account creation via the `CodeHashMod` https://github.com/privacy-scaling-explorations/zkevm-specs/blob/master/specs/tables.md#mpt_table . In particular it should support the transition where the account doesn't exist, and then with a {`CodeHashMod`, prev_value: 0, value: new_code_hash } a new account is created with:
- nonce: 0
- balance: 0
- code_hash: new_code_hash
- storage_root: empty_trie_root

By reading previous conversations I only found mentions of account creation proofs using `NonceMod` and `BalanceMod`.  But now we're using `codeHash` as a single field (in the state circuit) to encode existing/non-existing accounts, so it would be ideal to use `CodeHashMod` for account creation for consistency.  Hopefully @miha-stopar can confirm if the current mpt circuit supports account creation via `CodeHashMod`.

**Comment by ed255** [comment]
@lispc in this commit (it's in a branch) https://github.com/privacy-scaling-explorations/zkevm-circuits/commit/4e6e5560990c4f3f76131c89b89156e8e4018606 I've added the account lookup check to trigger also via `push_op_reversible`.  This causes the test `evm_circuit::execution::return_revert::test::test_return_root_create` to fail like this:
```
thread 'evm_circuit::execution::return_revert::test::test_return_root_create' panicked at 'RWTable Account field WRITE lookup to non-existing account rwc: 9, op: AccountOp { addr: 0xed59714e286e0058f3160cc1bc7506e6f06add3c, field: Balance, val_prev: 0x0, val: 0x0 }', bus-mapping/src/circuit_input_builder/input_state_ref.rs:302:13
```
This must come from the transfer to a non-existing account.

Since you're currently working on fixing this, I won't work on this for now; feel free to integrate the commit (or a part of it) in your branch if you do a PR :)

**Comment by miha-stopar** [comment]
> By reading previous conversations I only found mentions of account creation proofs using `NonceMod` and `BalanceMod`. But now we're using `codeHash` as a single field (in the state circuit) to encode existing/non-existing accounts, so it would be ideal to use `CodeHashMod` for account creation for consistency. Hopefully @miha-stopar can confirm if the current mpt circuit supports account creation via `CodeHashMod`.

Yes, it is possible to create an account by using `CodeHashMod`. Implicit leaf creation works for any leaf property, because when there is a change in a leaf that does not exist, a placeholder leaf is added as a witness. In this case, the last branch contains information about the leaf at `modified_node` being just a placeholder and the circuit ensures that when the leaf is a placeholder, the branch (last branch) children at `modified_node` is nil. So the `S` proof (the left one in MPT) ensures no leaf existed before the change and the `C` proof ensures the leaf has been created with the desired properties.

But to be on a safe side I added a test to the witness generator (previously there were tests for implicitly creating an account only for `NonceMod` and `BalanceMod`).

**Comment by ed255** [comment]
> Yes, it is possible to create an account by using `CodeHashMod`. Implicit leaf creation works for any leaf property, because when there is a change in a leaf that does not exist, a placeholder leaf is added as a witness. In this case, the last branch contains information about the leaf at `modified_node` being just a placeholder and the circuit ensures that when the leaf is a placeholder, the branch (last branch) children at `modified_node` is nil. So the `S` proof (the left one in MPT) ensures no leaf existed before the change and the `C` proof ensures the leaf has been created with the desired properties.
> 
> But to be on a safe side I added a test to the witness generator (previously there were tests for implicitly creating an account only for `NonceMod` and `BalanceMod`).

That's great! Thanks for adding such test :)

**Comment by lispc** [comment]
> Skip invalid tx taikoxyz/zkevm-circuits#32

great! we will have a look late this week!

**Comment by lispc** [comment]
> @lispc in this commit (it's in a branch) [4e6e556](https://github.com/privacy-scaling-explorations/zkevm-circuits/commit/4e6e5560990c4f3f76131c89b89156e8e4018606) I've added the account lookup check to trigger also via `push_op_reversible`. This causes the test `evm_circuit::execution::return_revert::test::test_return_root_create` to fail like this:
> 
> ```
> thread 'evm_circuit::execution::return_revert::test::test_return_root_create' panicked at 'RWTable Account field WRITE lookup to non-existing account rwc: 9, op: AccountOp { addr: 0xed59714e286e0058f3160cc1bc7506e6f06add3c, field: Balance, val_prev: 0x0, val: 0x0 }', bus-mapping/src/circuit_input_builder/input_state_ref.rs:302:13
> ```
> 
> This must come from the transfer to a non-existing account.
> 
> Since you're currently working on fixing this, I won't work on this for now; feel free to integrate the commit (or a part of it) in your branch if you do a PR :)

great! we will have a look late this week!

**Comment by lispc** [comment]
i am thinking another potential problem related.  In begin_tx gadget, we check 

```
let is_empty_code_hash =
            IsEqualGadget::construct(cb, phase2_code_hash.expr(), cb.empty_hash_rlc());
```

but in bus mapping, it is possible to put a Word::zero in that Rw than we pick the zero in gadget assignment so the phase2_code_hash also can be zero sometimes?    

also cc @han0110

**Comment by lispc** [comment]
i am thinking another potential problem related.  In begin_tx gadget, we check 

```
let is_empty_code_hash =
            IsEqualGadget::construct(cb, phase2_code_hash.expr(), cb.empty_hash_rlc());
```

but in bus mapping, it is possible to put a Word::zero in the codehash Rw than we pick the zero in gadget assignment so the phase2_code_hash also can be zero sometimes?    

https://github.com/privacy-scaling-explorations/zkevm-circuits/blob/3c621db347c18dbd0003add458efcc61b6e4ba1e/zkevm-circuits/src/evm_circuit/execution/begin_tx.rs#L291

also cc @han0110

**Comment by han0110** [comment]
> but in bus mapping, it is possible to put a Word::zero in the codehash Rw than we pick the zero in gadget assignment so the phase2_code_hash also can be zero sometimes?

Ah you are right, if the transaction doesn't have value, the account won't be created, then `phase2_code_hash` will stay `0` in this case.

So we might need to update the condition:

https://github.com/privacy-scaling-explorations/zkevm-circuits/blob/3c621db347c18dbd0003add458efcc61b6e4ba1e/zkevm-circuits/src/evm_circuit/execution/begin_tx.rs#L165

to also consider `is_zero_code_hash`.

**Comment by roynalnaruto** [comment]
@lispc I faced the above issue in a contract creation transaction as well, and I updated the bus-mapping logic to:
```rust
// Get code_hash of callee
      let (_, callee_account) = state.sdb.get_account(&call.address); &Account
      let callee_exists = !callee_account.is_empty(); bool
      let (callee_code_hash, is_empty_code_hash) = match (state.tx.is_create(), callee_exists) { U256, bool
          (true, _) => (call.code_hash.to_word(), false),
          (_, true) => {
              debug_assert_eq!(
                  callee_account.code_hash, call.code_hash,
                  "callee account's code hash: {:?}, call's code hash: {:?}",
                  callee_account.code_hash, call.code_hash
              );
              (
                  call.code_hash.to_word(),
                  call.code_hash.to_fixed_bytes() == *EMPTY_HASH,
              )
          }
          (_, false) => (Word::zero(), true),
      };
```

**Comment by ed255** [comment]
> > but in bus mapping, it is possible to put a Word::zero in the codehash Rw than we pick the zero in gadget assignment so the phase2_code_hash also can be zero sometimes?
> 
> Ah you are right, if the transaction doesn't have value, the account won't be created, then `phase2_code_hash` will stay `0` in this case.

I think that in general we should follow this rule for all ExecSteps that may create an account via transfer (this is BeginTx to empty account,  call{CALL, CALLCODE}):
- 1. Read callee code_hash to determine `is_empty = code_hash == 0`
- 2. if `balance > 0 & is_empty` then `write calle.code_hash 0 -> EMPTY_CODE_HASH` to create the callee account
- 3. if `balance > 0` then perform transfer

**Comment by ed255** [comment]
@lispc do you have any update on this issue?  If not, I would like to submit a PR with the checks from this commit https://github.com/privacy-scaling-explorations/zkevm-circuits/commit/4e6e5560990c4f3f76131c89b89156e8e4018606 and work on fixing the corresponding failures detected by the check.

**Comment by lispc** [comment]
some fixes are already in https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/1140 @ed255   we plan to re evalutate the issue after that merged.  of course you can also directly merge feature/extend-account-lookup-checks and scroll-tech:feat/begintx-contract-deploy to check for now

**Comment by lispc** [comment]
it is time to retry https://github.com/privacy-scaling-explorations/zkevm-circuits/compare/feature/extend-account-lookup-checks !
