### ISSUE TITLE
CALL inside tx init code panics

### ISSUE THREAD

**Issue by adria0** [privacy-scaling-explorations/zkevm-circuits#1153]
### What command(s) is the bug in?

`testool --inspect CREATE_ContractSuicideDuringInit_d0_g0_v0`

### Describe the bug

If the initcode of a transation (`to` is zero) contains a CALL to another contract, it fails with  a `RWTable Account field READ lookup to non-existing account` where the account that fails to read is the address of the new contract to create.

 trace:
```
[2023-02-09T11:55:34Z INFO  testool] Using suite 'default'
[2023-02-09T11:55:34Z INFO  testool] Parsing and compliling tests...
[2023-02-09T11:55:35Z INFO  testool] 9572 tests collected in tests/src/GeneralStateTestsFiller/**/*
+--------------------------------------------+------------------------------------------------------------------------------------------------------+
| id                                         | CREATE_ContractSuicideDuringInit_d0_g0_v0                                                            |
+--------------------------------------------+------------------------------------------------------------------------------------------------------+
| path                                       | tests/src/GeneralStateTestsFiller/stCreateTest/CREATE_ContractSuicideDuringInitFiller.json           |
+--------------------------------------------+------------------------------------------------------------------------------------------------------+
| coinbase                                   | 0x2adc25665018aa1fe0e6bc666dac8fc2697ff9ba                                                           |
+--------------------------------------------+------------------------------------------------------------------------------------------------------+
| difficulty                                 | 131072                                                                                               |
+--------------------------------------------+------------------------------------------------------------------------------------------------------+
| number                                     | 1                                                                                                    |
+--------------------------------------------+------------------------------------------------------------------------------------------------------+
| timestamp                                  | 1000                                                                                                 |
+--------------------------------------------+------------------------------------------------------------------------------------------------------+
| prev_hash                                  | 0x5e20a0453cecd065ea59c37ac63e079ee08998b6045136a8ce6635c7912ec0b6                                   |
+--------------------------------------------+------------------------------------------------------------------------------------------------------+
| sk                                         | 45a915e4d060149eb4365960e6a7a45f334393093061116b197e3240065ff2d8                                     |
+--------------------------------------------+------------------------------------------------------------------------------------------------------+
| from                                       | 0xa94f5374fce5edbc8e2a8697c15331677e6ebf0b                                                           |
+--------------------------------------------+------------------------------------------------------------------------------------------------------+
| to                                         | None                                                                                                 |
+--------------------------------------------+------------------------------------------------------------------------------------------------------+
| gas_limit                                  | 150000                                                                                               |
+--------------------------------------------+------------------------------------------------------------------------------------------------------+
| gas_price                                  | 10                                                                                                   |
+--------------------------------------------+------------------------------------------------------------------------------------------------------+
| nonce                                      | 0                                                                                                    |
+--------------------------------------------+------------------------------------------------------------------------------------------------------+
| value                                      | 0                                                                                                    |
+--------------------------------------------+------------------------------------------------------------------------------------------------------+
| data                                       | 6000600060006000600073c94f5374fce5edbc8e2a8697c15331677e6ebf0b61ea60f1506d64600c6000556000526005601b |
|                                            | f360005273c94f5374fce5edbc8e2a8697c15331677e6ebf0bff                                                 |
+--------------------------------------------+------------------------------------------------------------------------------------------------------+
| exception                                  | false                                                                                                |
+--------------------------------------------+------------------------------------------------------------------------------------------------------+
| 0x6295ee1b4f6dd65047762f924ecd367c17eabf8f |                                                                                                      |
+--------------------------------------------+------------------------------------------------------------------------------------------------------+
| 0xa94f5374fce5edbc8e2a8697c15331677e6ebf0b | balance :1000000000000                                                                               |
|                                            | code :                                                                                               |
|                                            | nonce :0                                                                                             |
+--------------------------------------------+------------------------------------------------------------------------------------------------------+
| 0xc94f5374fce5edbc8e2a8697c15331677e6ebf0b | balance :0 → 0                                                                                       |
|                                            | code :600c60015500                                                                                   |
|                                            | nonce :0                                                                                             |
|                                            | slot 1 :∅ → 12                                                                                       |
+--------------------------------------------+------------------------------------------------------------------------------------------------------+

[2023-02-09T11:55:35Z ERROR testool::utils] FAILED: false
[2023-02-09T11:55:35Z INFO  testool::utils] GAS: 83864
+----+--------------+-------+----------+-------+-----+--------------------------------------------------+--------+---------+
| PC | OP           | GAS   | GAS_COST | DEPTH | ERR | STACK                                            | MEMORY | STORAGE |
+----+--------------+-------+----------+-------+-----+--------------------------------------------------+--------+---------+
| 0  | PUSH1        | 95880 | 3        | 1     |     |                                                  |        |         |
+----+--------------+-------+----------+-------+-----+--------------------------------------------------+--------+---------+
| 2  | PUSH1        | 95877 | 3        | 1     |     | 0                                                |        |         |
+----+--------------+-------+----------+-------+-----+--------------------------------------------------+--------+---------+
| 4  | PUSH1        | 95874 | 3        | 1     |     | 0[2]                                             |        |         |
+----+--------------+-------+----------+-------+-----+--------------------------------------------------+--------+---------+
| 6  | PUSH1        | 95871 | 3        | 1     |     | 0[3]                                             |        |         |
+----+--------------+-------+----------+-------+-----+--------------------------------------------------+--------+---------+
| 8  | PUSH1        | 95868 | 3        | 1     |     | 0[4]                                             |        |         |
+----+--------------+-------+----------+-------+-----+--------------------------------------------------+--------+---------+
| 10 | PUSH20       | 95865 | 3        | 1     |     | 0[5]                                             |        |         |
+----+--------------+-------+----------+-------+-----+--------------------------------------------------+--------+---------+
| 31 | PUSH2        | 95862 | 3        | 1     |     | 0[5], 0xc94f5374fce5edbc8e2a8697c15331677e6ebf0b |        |         |
+----+--------------+-------+----------+-------+-----+--------------------------------------------------+--------+---------+
| 34 | CALL         | 95859 | 62600    | 1     |     | 0[5], 0xc94f5374fce5edbc8e2a8697c15331677e6ebf0b |        |         |
|    |              |       |          |       |     | 60000                                            |        |         |
+----+--------------+-------+----------+-------+-----+--------------------------------------------------+--------+---------+
| 0  | PUSH1        | 60000 | 3        | 2     |     |                                                  |        |         |
+----+--------------+-------+----------+-------+-----+--------------------------------------------------+--------+---------+
| 2  | PUSH1        | 59997 | 3        | 2     |     | 12                                               |        |         |
+----+--------------+-------+----------+-------+-----+--------------------------------------------------+--------+---------+
| 4  | SSTORE       | 59994 | 22100    | 2     |     | 12, 1                                            |        | 1: 12   |
+----+--------------+-------+----------+-------+-----+--------------------------------------------------+--------+---------+
| 5  | STOP         | 37894 | 0        | 2     |     |                                                  |        |         |
+----+--------------+-------+----------+-------+-----+--------------------------------------------------+--------+---------+
| 35 | POP          | 71153 | 2        | 1     |     | 1                                                |        |         |
+----+--------------+-------+----------+-------+-----+--------------------------------------------------+--------+---------+
| 36 | PUSH14       | 71151 | 3        | 1     |     |                                                  |        |         |
+----+--------------+-------+----------+-------+-----+--------------------------------------------------+--------+---------+
| 51 | PUSH1        | 71148 | 3        | 1     |     | 0x64600c6000556000526005601bf3                   |        |         |
+----+--------------+-------+----------+-------+-----+--------------------------------------------------+--------+---------+
| 53 | MSTORE       | 71145 | 6        | 1     |     | 0x64600c6000556000526005601bf3, 0                |        |         |
+----+--------------+-------+----------+-------+-----+--------------------------------------------------+--------+---------+
| 54 | PUSH20       | 71139 | 3        | 1     |     |                                                  |        |         |
+----+--------------+-------+----------+-------+-----+--------------------------------------------------+--------+---------+
| 75 | SELFDESTRUCT | 71136 | 5000     | 1     |     | 0xc94f5374fce5edbc8e2a8697c15331677e6ebf0b       |        |         |
+----+--------------+-------+----------+-------+-----+--------------------------------------------------+--------+---------+
thread 'main' panicked at 'RWTable Account field READ lookup to non-existing account rwc: 48, op: AccountOp { addr: 0x6295ee1b4f6dd65047762f924ecd367c17eabf8f, field: Balance, val_prev: 0x0, val: 0x0 }', bus-mapping/src/circuit_input_builder/input_state_ref.rs:309:13
stack backtrace:
   0: rust_begin_unwind
             at /rustc/015a824f2dffe32707fceb59c47effaf7b73486c/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/015a824f2dffe32707fceb59c47effaf7b73486c/library/core/src/panicking.rs:142:14
   2: bus_mapping::circuit_input_builder::input_state_ref::CircuitInputStateRef::check_update_sdb_account
   3: bus_mapping::circuit_input_builder::input_state_ref::CircuitInputStateRef::push_op
   4: <bus_mapping::evm::opcodes::callop::CallOpcode<_> as bus_mapping::evm::opcodes::Opcode>::gen_associated_ops
   5: bus_mapping::evm::opcodes::gen_associated_ops
   6: bus_mapping::circuit_input_builder::CircuitInputBuilder::handle_block
   7: testool::statetest::executor::run_test
   8: testool::run_single_test
   9: testool::main
```

Note: SELFDESTRUCT is not implemented, but is not rellevant

**Comment by han0110** [comment]
I think https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/1140 should fix this, since account `0x6295ee1b4f6dd65047762f924ecd367c17eabf8f` should have nonce `1` after it's created, so it won't be empty when doing the balance lookup.
