### ISSUE TITLE
Calling a contract that contains an invalid opcode (e.g. `DD`) panics

### ISSUE THREAD

**Issue by adria0** [privacy-scaling-explorations/zkevm-circuits#1160]
### What command(s) is the bug in?

`testool --oneliner 'call 10;DD'`

### Describe the bug

```
+--------------------------------------------+--------------------------------------------------------------------+
| coinbase                                   | 0x0000000000000000000000000000000000000000                         |
+--------------------------------------------+--------------------------------------------------------------------+
| difficulty                                 | 0                                                                  |
+--------------------------------------------+--------------------------------------------------------------------+
| number                                     | 1                                                                  |
+--------------------------------------------+--------------------------------------------------------------------+
| timestamp                                  | 1                                                                  |
+--------------------------------------------+--------------------------------------------------------------------+
| prev_hash                                  | 0x0000000000000000000000000000000000000000000000000000000000000000 |
+--------------------------------------------+--------------------------------------------------------------------+
| sk                                         | 0101010101010101010101010101010101010101010101010101010101010101   |
+--------------------------------------------+--------------------------------------------------------------------+
| from                                       | 0x1a642f0e3c3af545e7acbd38b07251b3990914f1                         |
+--------------------------------------------+--------------------------------------------------------------------+
| to                                         | Some(0x0000000000000000000000000000000000000010)                   |
+--------------------------------------------+--------------------------------------------------------------------+
| gas_limit                                  | 10000000                                                           |
+--------------------------------------------+--------------------------------------------------------------------+
| gas_price                                  | 1                                                                  |
+--------------------------------------------+--------------------------------------------------------------------+
| nonce                                      | 0                                                                  |
+--------------------------------------------+--------------------------------------------------------------------+
| value                                      | 0                                                                  |
+--------------------------------------------+--------------------------------------------------------------------+
| data                                       |                                                                    |
+--------------------------------------------+--------------------------------------------------------------------+
| exception                                  | false                                                              |
+--------------------------------------------+--------------------------------------------------------------------+
| 0x0000000000000000000000000000000000000010 | balance :0                                                         |
|                                            | code :dd                                                           |
|                                            | nonce :1                                                           |
+--------------------------------------------+--------------------------------------------------------------------+
| 0x1a642f0e3c3af545e7acbd38b07251b3990914f1 | balance :1000000000000000000                                       |
|                                            | code :                                                             |
|                                            | nonce :0                                                           |
+--------------------------------------------+--------------------------------------------------------------------+

+----+--------------+---------+----------+-------+-----+-------+--------+---------+
| PC | OP           | GAS     | GAS_COST | DEPTH | ERR | STACK | MEMORY | STORAGE |
+----+--------------+---------+----------+-------+-----+-------+--------+---------+
| 0  | INVALID(221) | 9979000 | 0        | 1     |     |       |        |         |
+----+--------------+---------+----------+-------+-----+-------+--------+---------+
thread 'main' panicked at 'RWTable Account field WRITE lookup to non-existing account rwc: 32, op: AccountOp { addr: 0x0000000000000000000000000000000000000000, field: Balance, val_prev: 0x0, val: 0x0 }', bus-mapping/src/circuit_input_builder/input_state_ref.rs:309:13
```

**Comment by ed255** [comment]
The panic message `thread 'main' panicked at 'RWTable Account field WRITE lookup to non-existing account rwc: 32, op: AccountOp { addr: 0x0000000000000000000000000000000000000000, field: Balance, val_prev: 0x0, val: 0x0 }', bus-mapping/src/circuit_input_builder/input_state_ref.rs:309:13` doesn't seem to be directly related to having invalid bytes in the contract.

Support for the invalid opcode state was merged on February 10th via https://github.com/privacy-scaling-explorations/zkevm-circuits/issues/1138 , so maybe this is already fixed?  @adria0 whenever you have some time, could you try this test again?
