### ISSUE TITLE
MockProver::assert_satisfied panics unexpectedly

### ISSUE THREAD

**Issue by ed255** [privacy-scaling-explorations/zkevm-circuits#974]
The `MockProver` from halo2 recently added a new function called `assert_satisfied` which runs the mock prover and pretty prints the errors, which is really convenient for debugging.  Basically it calls `VerifyFailure::emit` on every error.  Currently we're not using this output and I think it would be very useful!

Unfortunately right now the `VerifyFailure::emit` panics in the middle of the pretty printing process.

Steps to reproduce:
- 1st use the `assert_satisifed` method:
```diff
diff --git a/zkevm-circuits/src/evm_circuit.rs b/zkevm-circuits/src/evm_circuit.rs
index eb189f53..e837172d 100644
--- a/zkevm-circuits/src/evm_circuit.rs
+++ b/zkevm-circuits/src/evm_circuit.rs
@@ -460,7 +460,10 @@ pub mod test {
 
         let circuit = get_test_cicuit_from_block(block);
         let prover = MockProver::<F>::run(k, &circuit, power_of_randomness).unwrap();
-        prover.verify_at_rows_par(active_gate_rows.into_iter(), active_lookup_rows.into_iter())
+        // prover.verify_at_rows_par(active_gate_rows.into_iter(),
+        // active_lookup_rows.into_iter())
+        prover.assert_satisfied();
+        Ok(())
     }
 }
```
- 2nd change a circuit to make it fail
```diff
diff --git a/zkevm-circuits/src/evm_circuit/execution/add_sub.rs b/zkevm-circuits/src/evm_circuit/execution/add_sub.rs
index 47e68c70..e61c434c 100644
--- a/zkevm-circuits/src/evm_circuit/execution/add_sub.rs
+++ b/zkevm-circuits/src/evm_circuit/execution/add_sub.rs
@@ -88,7 +88,7 @@ impl<F: Field> ExecutionGadget<F> for AddSubGadget<F> {
         } else {
             [step.rw_indices[0], step.rw_indices[1], step.rw_indices[2]]
         };
-        let [a, b, c] = indices.map(|idx| block.rws[idx].stack_value());
+        let [a, c, b] = indices.map(|idx| block.rws[idx].stack_value());
         self.add_words.assign(region, offset, [a, b], c)?;
         self.is_sub.assign(
             region,
```
- 3rd run the test for that circuit
```
RUST_BACKTRACE=1 cargo test add_gadget_simple --all-features -- --nocapture
```

Output:
```
error: constraint not satisfied
  Cell layout in region 'Execution step':
    | Offset | A43|
    +--------+----+
    |   28   | x0 | <--{ Gate 'ADD_SUB' applied here

  Constraint 'sum(addends_lo) == sum_lo + carry_lo ⋅ 2^128':
thread 'evm_circuit::execution::add_sub::test::add_gadget_simple' panicked at 'called `Option::unwrap()` on a `None` value', 
/home/dev/.cargo/git/checkouts/halo2-afe2d0b0be6b3c3a/a9e99a7/halo2_proofs/src/dev/failure/emitter.rs:131:18
stack backtrace:
   0: rust_begin_unwind
             at /rustc/015a824f2dffe32707fceb59c47effaf7b73486c/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/015a824f2dffe32707fceb59c47effaf7b73486c/library/core/src/panicking.rs:142:14
   2: core::panicking::panic
             at /rustc/015a824f2dffe32707fceb59c47effaf7b73486c/library/core/src/panicking.rs:48:5
   3: core::option::Option<T>::unwrap
             at /rustc/015a824f2dffe32707fceb59c47effaf7b73486c/library/core/src/option.rs:775:21
   4: halo2_proofs::dev::failure::emitter::expression_to_string::{{closure}}
             at /home/dev/.cargo/git/checkouts/halo2-afe2d0b0be6b3c3a/a9e99a7/halo2_proofs/src/dev/failure/emitter.rs:121:13
   5: halo2_proofs::plonk::circuit::Expression<F>::evaluate
             at /home/dev/.cargo/git/checkouts/halo2-afe2d0b0be6b3c3a/a9e99a7/halo2_proofs/src/plonk/circuit.rs:712:42
   6: halo2_proofs::plonk::circuit::Expression<F>::evaluate
             at /home/dev/.cargo/git/checkouts/halo2-afe2d0b0be6b3c3a/a9e99a7/halo2_proofs/src/plonk/circuit.rs:716:25
   7: halo2_proofs::plonk::circuit::Expression<F>::evaluate
             at /home/dev/.cargo/git/checkouts/halo2-afe2d0b0be6b3c3a/a9e99a7/halo2_proofs/src/plonk/circuit.rs:743:25
   8: halo2_proofs::plonk::circuit::Expression<F>::evaluate
             at /home/dev/.cargo/git/checkouts/halo2-afe2d0b0be6b3c3a/a9e99a7/halo2_proofs/src/plonk/circuit.rs:758:25
   9: halo2_proofs::plonk::circuit::Expression<F>::evaluate
             at /home/dev/.cargo/git/checkouts/halo2-afe2d0b0be6b3c3a/a9e99a7/halo2_proofs/src/plonk/circuit.rs:758:25
  10: halo2_proofs::plonk::circuit::Expression<F>::evaluate
             at /home/dev/.cargo/git/checkouts/halo2-afe2d0b0be6b3c3a/a9e99a7/halo2_proofs/src/plonk/circuit.rs:770:25
  11: halo2_proofs::dev::failure::emitter::expression_to_string
             at /home/dev/.cargo/git/checkouts/halo2-afe2d0b0be6b3c3a/a9e99a7/halo2_proofs/src/dev/failure/emitter.rs:103:5
  12: halo2_proofs::dev::failure::render_constraint_not_satisfied
             at /home/dev/.cargo/git/checkouts/halo2-afe2d0b0be6b3c3a/a9e99a7/halo2_proofs/src/dev/failure.rs:348:9
  13: halo2_proofs::dev::failure::VerifyFailure::emit
             at /home/dev/.cargo/git/checkouts/halo2-afe2d0b0be6b3c3a/a9e99a7/halo2_proofs/src/dev/failure.rs:539:17
  14: halo2_proofs::dev::MockProver<F>::assert_satisfied
             at /home/dev/.cargo/git/checkouts/halo2-afe2d0b0be6b3c3a/a9e99a7/halo2_proofs/src/dev.rs:1312:17
  15: zkevm_circuits::evm_circuit::test::run_test_circuit
             at ./src/evm_circuit.rs:465:9
  16: zkevm_circuits::test_util::test_circuits_witness_block
             at ./src/test_util.rs:104:9
  17: zkevm_circuits::test_util::run_test_circuits
             at ./src/test_util.rs:62:5
  18: zkevm_circuits::evm_circuit::execution::add_sub::test::test_ok
             at ./src/evm_circuit/execution/add_sub.rs:122:13
  19: zkevm_circuits::evm_circuit::execution::add_sub::test::add_gadget_simple
             at ./src/evm_circuit/execution/add_sub.rs:132:9
  20: zkevm_circuits::evm_circuit::execution::add_sub::test::add_gadget_simple::{{closure}}
             at ./src/evm_circuit/execution/add_sub.rs:131:5
  21: core::ops::function::FnOnce::call_once
             at /rustc/015a824f2dffe32707fceb59c47effaf7b73486c/library/core/src/ops/function.rs:248:5
  22: core::ops::function::FnOnce::call_once
             at /rustc/015a824f2dffe32707fceb59c47effaf7b73486c/library/core/src/ops/function.rs:248:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
test evm_circuit::execution::add_sub::test::add_gadget_simple ... FAILED

failures:

failures:
    evm_circuit::execution::add_sub::test::add_gadget_simple

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 222 filtered out; finished in 44.04s
```

NOTE: Probably this needs to be fixed in https://github.com/privacy-scaling-explorations/halo2

**Comment by CPerezz** [comment]
Thanks for filling this @ed255

**Comment by CPerezz** [comment]
Transferring this to our fork.
